server {
    server_name worldmonitor.skyreel.art;

    # Allow ACME HTTP-01 challenge for Certbot
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/worldmonitor.skyreel.art/public;
        try_files $uri =404;
    }

    location /wm/ {
        proxy_pass http://127.0.0.1:3400;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/worldmonitor.skyreel.art/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/worldmonitor.skyreel.art/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = worldmonitor.skyreel.art) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name worldmonitor.skyreel.art;
    return 404; # managed by Certbot
}
